### ISSUE TITLE
Implement site login form data support

### ISSUE THREAD

**Issue by bdunogier** [wallabag/guzzle-site-authenticator#7]
On some sites, the login process expects POST data based on dynamic fields from the site's form.

It should be fairly easy to cover with the `LoginFormAuthenticator`. Since it is a potentially common feature, properties can be added to `SiteConfig`, something like `loginFormFields`.

If it contains values, the authenticator will:
- send a GET request to the login form URI
  this hints that we need another URI, maybe optional, since form & action might not use the same)
- It will read the form fields from the Response (xpath, maybe with the action ?)
- Add the requested form fields found in the Reponse's form to the POST fields

**Comment by j0k3r** [comment]
I guess we can close that issue @bdunogier?

**Comment by bdunogier** [comment]
Yep, it is implemented in #14
